export const DATA_DOG_SITE = process.env.DATA_DOG_SITE ?? 'datadoghq.com'
export const DATA_DOG_RUM_APPLICATION_ID = process.env.DATA_DOG_RUM_APPLICATION_ID ?? ''
export const DATA_DOG_CLIENT_TOKEN = process.env.DATA_DOG_CLIENT_TOKEN ?? ''
export const DATA_DOG_CLIENT_TOKEN = process.env.DATA_DOG_CLIENT_TOKEN ?? ''
export const DATA_DOG_SERVICE_NAME = process.env.DATA_DOG_SERVICE_NAME ?? 'zed-micro-fe-starter'
